export const data = [
  {
    id: 1,
    author: '― Mark Manson',
    description: `“Being wrong opens us up to the possibility of change. Being wrong brings the opportunity for growth.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 2,
    author: '― Mark Manson',
    description: `“Maturity is what happens when one learns to only give a fuck about what’s truly fuckworthy.”
`,
    amount: 1,
    categories: ['Life-lessons'],
  },
  {
    id: 3,
    author: '― Mark Manson',
    description: `“This is the most simple and basic component of life: our struggles determine our successes.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 4,
    author: '― Mark Manson',
    description: `“Don’t just sit there. Do something. The answers will follow.”
`,
    amount: 1,
    categories: ['progress'],
  },
  {
    id: 5,
    author: '― Sylvester Stallone',
    description: `“Consider the source...Don't be a fool by listening to a fool.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 6,
    author: '― Mark Manson',
    description: `“Who you are is defined by what you’re willing to struggle for.”
`,
    amount: 1,
    categories: ['personal development'],
  },
  {
    id: 7,
    author: '― Sylvester Stallone',
    description: `Life's not about how hard of a hit you can give... it's about how many you can take, and still keep moving forward.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 8,
    author: '- Marcus Aurelius',
    description: `"When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love ... then make that day count!
"`,
    amount: 1,
    categories: ['motivation'],
  },
  {
    id: 9,
    author: '- Marcus Aurelius',
    description: `"Do not be wise in words - be wise in deeds.
"`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 10,
    author: '- Marcus Aurelius',
    description: `"The opinion of 10,000 men is of no value if none of them know anything about the subject."
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 11,
    author: '- Marcus Aurelius',
    description: `"It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinions than our own."
`,
    amount: 1,
    categories: ['love', 'care'],
  },
  {
    id: 12,
    author: '― Arnold Schwarzenegger',
    description: `“There are no shortcuts—everything is reps, reps, reps.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 13,
    author: '― Arnold Schwarzenegger',
    description: `“What is the point of being on this Earth if you are going to be like everyone else?”
`,
    amount: 1,
    categories: ['inspiration'],
  },
  {
    id: 14,
    author: '― Arnold Schwarzenegger',
    description: `“Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 15,
    author: '― Jocko Willink',
    description: `“There is no easy way.
There is only hard work, late nights, early mornings, practice, rehearsal, repetition, study, sweat, blood, toil, frustration, and discipline.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 16,
    author: '― Jocko Willink',
    description: `“It’s not what you preach, it’s what you tolerate.”
`,
    amount: 1,
    categories: ['attitude'],
  },
  {
    id: 17,
    author: '― Naval Ravikant',
    description: `“All greatness comes from suffering.”
`,
    amount: 1,
    categories: ['inspiration'],
  },
  {
    id: 18,
    author: '― Naval Ravikant',
    description: `“Escape competition through authenticity”
`,
    amount: 1,
    categories: ['personal development'],
  },
  {
    id: 19,
    author: '― Naval Ravikant',
    description: `“You make your own luck if you stay at it long enough.”
`,
    amount: 1,
    categories: ['personal development'],
  },
  {
    id: 20,
    author: '― Maya Angelou',
    description: `“When someone shows you who they are believe them the first time.”
`,
    amount: 1,
    categories: ['impression'],
  },
  {
    id: 21,
    author: '― Albert Einstein',
    description: `“A clever person solves a problem. A wise person avoids it.”
`,
    amount: 1,
    categories: ['wisdom'],
  },
  {
    id: 22,
    author: '― Satchel Paige',
    description: `“You win a few, you lose a few. Some get rained out. But you got to dress for all of them.”
`,
    amount: 1,
    categories: ['life-lessons'],
  },
  {
    id: 23,
    author: '― Roy T. Bennett',
    description: `“You attract who you are being. When you work at being the type of person that you want to attract, you attract those kinds of people into your life.”
"`,
    amount: 1,
    categories: ['motivation', 'inspiration'],
  },
  {
    id: 24,
    author: '― Brian Rathbone',
    description: `“Wisdom is the reward for surviving our own stupidity.”
`,
    amount: 1,
    categories: ['wisdom'],
  },
  {
    id: 25,
    author: '― Roy T. Bennett',
    description: `“Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.”
`,
    amount: 1,
    categories: ['motivation'],
  },
  {
    id: 26,
    author: '― Socrates',
    description: `“The only true wisdom is in knowing you know nothing.”
`,
    amount: 1,
    categories: ['wisdom'],
  },
  {
    id: 27,
    author: '― Aristotle',
    description: `“Knowing yourself is the beginning of all wisdom.”
`,
    amount: 1,
    categories: ['self discovery'],
  },
  {
    id: 28,
    author: '― Mark Twain',
    description: `“Never tell the truth to people who are not worthy of it.”`,
    amount: 1,
    categories: ['truth'],
  },
  {
    id: 29,
    author: '― Miyamoto Musash',
    description: `“The only reason a warrior is alive is to fight, and the only reason a warrior fights is to win”`,
    amount: 1,
    categories: ['strategy'],
  },
  {
    id: 30,
    author: '― Miyamoto Musash',
    description: `"If you wish to control others you must first control yourself"`,
    amount: 1,
    categories: ['self control'],
  },
  {
    id: 31,
    amount: 1,
    categories: ['Courage'],
    author: '- Oprah Winfrey',
    description: `"The only courage anybody ever needs is the courage to follow your own dreams."`,
  },
  {
    id: 32,
    amount: 1,
    categories: ['Perseverance'],
    author: '- Michael Jordan',
    description: `"I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed."`,
  },
  {
    id: 33,
    amount: 1,
    categories: ['Time'],
    author: '- Unknown',
    description: `"Yesterday is history. Tomorrow is a mystery. Today is a gift. That’s why it’s called the present."`,
  },
  {
    id: 34,
    amount: 1,
    categories: ['Procrastination'],
    author: '- Napoleon Hill',
    description: `"Don\'t wait. The time will never be just right."`,
  },
  {
    id: 35,
    amount: 1,
    categories: ['Success', 'Perseverance'],
    author: '- Walt Disney',
    description: `"All our dreams can come true, if we have the courage to pursue them."`,
  },
  {
    id: 36,
    amount: 1,
    categories: ['Dreams', 'Motivation'],
    author: '- Eleanor Roosevelt',
    description: `"The future belongs to those who believe in the beauty of their dreams."`,
  },
  {
    id: 37,
    amount: 1,
    categories: ['Dreams', 'Opportunity'],
    author: '- Pablo Picasso',
    description: `"Everything you can imagine is real."`,
  },
  {
    id: 38,
    amount: 1,
    categories: ['Life', 'Perspective'],
    author: '- Charles Swindoll',
    description: `"Life is 10% what happens to me and 90% of how I react to it."`,
  },
  {
    id: 39,
    amount: 1,
    categories: ['Dreams', 'Life'],
    author: '- Henry David Thoreau',
    description: `"Go confidently in the direction of your dreams. Live the life you have imagined."`,
  },
  {
    id: 40,
    amount: 1,
    categories: ['Life', 'Plans'],
    author: '- John Lennon',
    description: `"Life is what happens to you while you’re busy making other plans."`,
  },
  {
    id: 41,
    amount: 1,
    categories: ['Time', 'Opportunity'],
    author: '- Chinese Proverb',
    description: `"The best time to plant a tree was 20 years ago. The second best time is now."`,
  },
  {
    id: 46,
    amount: 1,
    categories: ['Dreams', 'Belief'],
    author: '- Napoleon Hill',
    description: `"Whatever the mind of man can conceive and believe, it can achieve."`,
  },
  {
    id: 47,
    amount: 1,
    categories: ['Dreams', 'Failure'],
    author: '- Norman Vaughan',
    description: `"Dream big and dare to fail."`,
  },
  {
    id: 48,
    amount: 1,
    categories: ['Inspiration', 'Helping'],
    author: '- Booker T. Washington',
    description: `"If you want to lift yourself up, lift up someone else."`,
  },
  {
    id: 49,
    amount: 1,
    categories: ['Planning', 'Execution'],
    author: '- George Patton',
    description: `"A good plan violently executed now is better than a perfect plan executed next week."`,
  },
  {
    id: 50,
    amount: 1,
    categories: ['Journey', 'Starting'],
    author: '- Lao Tzu',
    description: `"A journey of a thousand miles must begin with a single step."`,
  },
  {
    id: 51,
    amount: 1,
    categories: ['Courage', 'Decision'],
    author: '- Spencer Johnson',
    description: `"What would you do if you weren't afraid?"`,
  },
  {
    id: 52,
    amount: 1,
    categories: ['Leadership', 'Influence'],
    author: '- Brian Tracy',
    description: `"Become the kind of leader that people would follow voluntarily; even if you had no title or position."`,
  },
  {
    id: 53,
    amount: 1,
    categories: ['Goal', 'Planning'],
    author: '- Larry Elder',
    description: `"A goal without a plan is just a wish."`,
  },
  {
    id: 53,
    amount: 1,
    categories: ['Leadership', 'Influence'],
    author: '- Lao Tzu',
    description: `"A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves."`,
  },
  {
    id: 54,
    amount: 1,
    categories: ['Life', 'Value'],
    author: '- Charles Darwin',
    description: `"A man who dares to waste one hour of life has not discovered the value of life."`,
  },
  {
    id: 55,
    amount: 1,
    categories: ['Mistakes', 'Learning'],
    author: '- Albert Einstein',
    description: `"A person who never made a mistake never tried anything new."`,
  },
  {
    id: 56,
    amount: 1,
    categories: ['Richness', 'Family'],
    author: '- Unknown',
    description: `"A truly rich man is one whose children run into his arms when his hands are empty."`,
  },
  {
    id: 57,
    amount: 1,
    categories: ['Leadership'],
    author: '- Douglas MacArthur',
    description: `"A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others."`,
  },
  {
    id: 58,
    amount: 1,
    categories: ['Ideas', 'Power'],
    author: '- Victor Hugo',
    description: `"All the forces in the world are not so powerful as an idea whose time has come."`,
  },
  {
    id: 59,
    amount: 1,
    categories: ['Adaptability'],
    author: '- Publilius Syrus',
    description: `"Anyone can hold the helm when the sea is calm."`,
  },
  {
    id: 60,
    amount: 1,
    categories: ['Goals', 'Achievement'],
    author: '- Bruce Lee',
    description: `"A goal is not always meant to be reached; it often serves simply as something to aim at."`,
  },
  {
    id: 61,
    amount: 1,
    categories: ['Achievement', 'Purpose'],
    author: '- W. Clement Stone',
    description: `"Definiteness of purpose is the starting point of all achievement."`,
  },
  {
    id: 62,
    amount: 1,
    categories: ['Perseverance'],
    author: '- Japanese Proverb',
    description: `"Fall seven times and stand up eight."`,
  },
  {
    id: 63,
    amount: 1,
    categories: ['Dreams', 'Success'],
    author: '- Henry Thoreau',
    description: `"If one advances confidently in the direction of his dreams, and endeavors to live the life he has imagined, he will meet with a success unexpected in common hours."`,
  },
  {
    id: 64,
    amount: 1,
    categories: ['Goals', 'Dreams'],
    author: '- Diana Scharf Hunt',
    description: `"Goals are dreams with deadlines."`,
  },
  {
    id: 65,
    amount: 1,
    categories: ['Goals'],
    author: '- Swami Vivekananda',
    description: `"Arise, awake, stop not until your goal is achieved."`,
  },
  {
    id: 66,
    amount: 1,
    categories: ['Belief'],
    author: '- Stephen Covey',
    description: `"I am not a product of my circumstances. I am a product of my decisions."`,
  },
  {
    id: 67,
    amount: 1,
    categories: ['Success', 'Failure'],
    author: '- Herbert Swope',
    description: `"I cannot give you the formula for success, but I can give you the formula for failure, which is: Try to please everybody."`,
  },
  {
    id: 68,
    amount: 1,
    categories: ['Time', 'Efficiency'],
    author: '- Lord Chesterfield',
    description: `"I recommend to you to take care of the minutes; for hours will take care of themselves."`,
  },
  {
    id: 69,
    amount: 1,
    categories: ['Opportunity'],
    author: '- Sheryl Sandberg',
    description: `"If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on."`,
  },
  {
    id: 70,
    amount: 1,
    categories: ['Possibilities', 'Foolishness'],
    author: '- Napoleon Bonaparte',
    description: `"Impossible is a word to be found only in the dictionary of fools."`,
  },
  {
    id: 71,
    amount: 1,
    categories: ['Passion', 'Work'],
    author: '- Steve Jobs',
    description: `"The only way to do great work is to love what you do."`,
  },
  {
    id: 72,
    amount: 1,
    categories: ['Courage'],
    author: '- Tibetan saying',
    description: `"It is better to have lived one day as a tiger than a thousand years as a sheep."`,
  },
  {
    id: 73,
    amount: 1,
    categories: ['Life'],
    author: '- Abraham Lincoln',
    description: `"It’s not the years in your life that count. It’s the life in your years."`,
  },
  {
    id: 74,
    amount: 1,
    categories: ['Challenges'],
    author: '- Richard Branson',
    description: `"My interest in life comes from setting myself huge, apparently unachievable challenges and trying to rise above them."`,
  },
  {
    id: 75,
    amount: 1,
    categories: ['Leadership'],
    author: '- General George Patton',
    description: `"Lead me, follow me, or get out of my way."`,
  },
  {
    id: 76,
    amount: 1,
    categories: ['Wealth', 'Price'],
    author: '- Alexander Bloch',
    description: `"Money is a wonderful thing, but it is possible to pay too high a price for it."`,
  },
  {
    id: 77,
    amount: 1,
    categories: ['Perseverance'],
    author: '- Winston Churchill',
    description: `"If you’re going through hell, keep going!"`,
  },
  {
    id: 78,
    amount: 1,
    categories: ['Dreams'],
    author: '- Les Brown',
    description: `"Shoot for the moon. Even if you miss, you'll land among the stars."`,
  },
  {
    id: 79,
    amount: 1,
    categories: ['Life', 'Moments'],
    author: '- Maya Angelou',
    description: `"Life is not measured by the number of breaths we take, but by the moments that take our breath away."`,
  },
  {
    id: 80,
    amount: 1,
    categories: ['Influence'],
    author: '- Chinese Proverb',
    description: `"Not the cry, but the flight of a wild duck, leads the flock to fly and follow."`,
  },
  {
    id: 81,
    amount: 1,
    categories: ['Success', 'Value'],
    author: '- Albert Einstein',
    description: `"Strive not to be a success, but rather to be of value."`,
  },
  {
    id: 82,
    amount: 1,
    categories: ['Time', 'Efficiency'],
    author: '- Lord Chesterfield',
    description: `"Take care of the minutes and the hours will take care of themselves."`,
  },
  {
    id: 83,
    amount: 1,
    categories: ['Dreams', 'Realism'],
    author: '- Will Smith',
    description: `"The greatest dreams are always unrealistic."`,
  },
  {
    id: 84,
    amount: 1,
    categories: ['Mindset'],
    author: '- Buddha',
    description: `"The mind is everything. What you think you become."`,
  },
  {
    id: 85,
    amount: 1,
    categories: ['Determination'],
    author: '- Ayn Rand',
    description: `"The question isn’t who is going to let me; it’s who is going to stop me."`,
  },
  {
    id: 86,
    amount: 1,
    categories: ['Life', 'Purpose'],
    author: '- Mark Twain',
    description: `"The two most important days in your life are the day you are born and the day you find out why."`,
  },
  {
    id: 87,
    amount: 1,
    categories: ['Excellence'],
    author: '- Roger Staubach',
    description: `"There are no traffic jams along the extra mile."`,
  },
  {
    id: 88,
    amount: 1,
    categories: ['Efficiency'],
    author: '- Unknown',
    description: `"We are too busy mopping the floor to turn off the faucet."`,
  },
  {
    id: 89,
    amount: 1,
    categories: ['Impact'],
    author: '- Stephen Covey',
    description: `"What you do has far greater impact than what you say."`,
  },
  {
    id: 90,
    amount: 1,
    categories: ['Leadership'],
    author: '- Rear Admiral Grace Murray Hopper',
    description: `"You manage things; you lead people."`,
  },
  {
    id: 91,
    amount: 1,
    categories: ['Value', 'Selflessness'],
    author: '- Charles Dickens',
    description: `"A day wasted on others is not wasted on one’s self."`,
  },
  {
    id: 92,
    amount: 1,
    categories: ['Leadership'],
    author: '- John C. Maxwell',
    description: `"A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit."`,
  },
  {
    id: 93,
    amount: 1,
    categories: ['Leadership', 'Hope'],
    author: '- Napoleon Bonaparte',
    description: `"A leader is a dealer in hope."`,
  },
  {
    id: 94,
    amount: 1,
    categories: ['Leadership'],
    author: '- John C. Maxwell',
    description: `"A leader is one who knows the way, goes the way, and shows the way."`,
  },
  {
    id: 95,
    amount: 1,
    categories: ['Leadership'],
    author: '- Rosalynn Carter',
    description: `"A leader takes people where they want to go. A great leader takes people where they don’t necessarily want to go, but ought to be."`,
  },
  {
    id: 96,
    amount: 1,
    categories: ['Leadership'],
    author: '- Max Lucado',
    description: `"A man who wants to lead the orchestra must turn his back on the crowd."`,
  },
  {
    id: 97,
    amount: 1,
    categories: ['Time'],
    author: '- Maya Angelou',
    description: `"All great achievements require time."`,
  },
  {
    id: 98,
    amount: 1,
    categories: ['Goals'],
    author: '- Norman Vincent Peale',
    description: `"All successful people have a goal. No one can get anywhere unless he knows where he wants to go and what he wants to be or do."`,
  },
  {
    id: 99,
    amount: 1,
    categories: ['Time'],
    author: '- Baltasar Gracián',
    description: `"All that really belongs to us is time; even he who has nothing else has that."`,
  },
  {
    id: 100,
    amount: 1,
    categories: ['Preparation'],
    author: '- Chinese Proverb',
    description: `"All the flowers of all of the tomorrows are in the seeds of today."`,
  },
  {
    id: 101,
    amount: 1,
    categories: ['Self-Reflection'],
    author: '- Socrates',
    description: `"An unexamined life is not worth living."`,
  },
  {
    id: 102,
    amount: 1,
    categories: ['Motivation'],
    author: '- Swami Vivekananda',
    description: `"Arise, awake, stop not until your goal is achieved."`,
  },
  {
    id: 103,
    amount: 1,
    categories: ['Success'],
    author: '- Mary Kay Ash',
    description: `"An average person with average talents and ambition and average education, can outstrip the most brilliant genius in our society if that person has clear, focused goals."`,
  },
  {
    id: 104,
    amount: 1,
    categories: ['Progress'],
    author: '- John Dewey',
    description: `"Arriving at one goal is the starting point to another."`,
  },
  {
    id: 105,
    amount: 1,
    categories: ['Seeking'],
    author: '- Jesus',
    description: `"Ask and it will be given to you; search, and you will find; knock and the door will be opened for you."`,
  },
  {
    id: 106,
    amount: 1,
    categories: ['Time'],
    author: '- Unknown',
    description: `"Be mindful of how you approach time. Watching the clock is not the same."`,
  },
  {
    id: 107,
    amount: 1,
    categories: ['Leadership', 'Personal Growth'],
    author: '- Jack Welch',
    description: `"Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others."`,
  },
  {
    id: 108,
    amount: 1,
    categories: ['Belief'],
    author: '- Theodore Roosevelt',
    description: `"Believe you can and you’re halfway there."`,
  },
  {
    id: 109,
    amount: 1,
    categories: ['Purpose'],
    author: '- Ancient Indian Proverb',
    description: `"Certain things catch your eye, but pursue only those that capture the heart."`,
  },
  {
    id: 110,
    amount: 1,
    categories: ['Challenges', 'Life'],
    author: '- Joshua J. Marine',
    description: `"Challenges are what make life interesting and overcoming them is what makes life meaningful."`,
  },
  {
    id: 111,
    amount: 1,
    categories: ['Destiny', 'Choice'],
    author: '- William Jennings Bryan',
    description: `"Destiny is no matter of chance. It is a matter of choice. It is not a thing to be waited for; it is a thing to be achieved."`,
  },
  {
    id: 112,
    amount: 1,
    categories: ['Discipline'],
    author: '- Jim Rohn',
    description: `"Discipline is the bridge between goals and accomplishment."`,
  },
  {
    id: 113,
    amount: 1,
    categories: ['Progress'],
    author: '- Alfred A. Montapert',
    description: `"Do not confuse motion and progress. A rocking horse keeps moving but does not make any progress."`,
  },
  {
    id: 114,
    amount: 1,
    categories: ['Mindfulness'],
    author: '- Buddha',
    description: `"Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment."`,
  },
  {
    id: 115,
    amount: 1,
    categories: ['Action', 'Opportunity'],
    author: '- Teddy Roosevelt',
    description: `"Do what you can, where you are, with what you have."`,
  },
  {
    id: 116,
    amount: 1,
    categories: ['Integrity'],
    author: '- Eleanor Roosevelt',
    description: `"Do what you feel in your heart to be right – for you’ll be criticized anyway."`,
  },
  {
    id: 117,
    amount: 1,
    categories: ['Time Management'],
    author: '- Charles Richards',
    description: `"Don’t be fooled by the calendar. There are only as many days in the year as you make use of. One man gets only a week’s value out of a year while another man gets a full year’s value out of a week."`,
  },
  {
    id: 118,
    amount: 1,
    categories: ['Decision Making'],
    author: '- Peter Turla',
    description: `"Don’t be stomping on ants when you have elephants to feed."`,
  },
  {
    id: 119,
    amount: 1,
    categories: ['Decision Making'],
    author: '- Peter Turla',
    description: `"Don’t spend a dollar’s worth of time on a ten-cent decision."`,
  },
  {
    id: 120,
    amount: 1,
    categories: ['Time'],
    author: '- Benjamin Franklin',
    description: `"Dost thou love life? Then do not squander time, for that’s the stuff that life is made of."`,
  },
  {
    id: 121,
    amount: 1,
    categories: ['Planning'],
    author: '- Gloria Steinem',
    description: `"Dreaming, after all, is a form of planning."`,
  },
  {
    id: 122,
    amount: 1,
    categories: ['Creativity'],
    author: '- Pablo Picasso',
    description: `"

Every child is an artist. The problem is how to remain an artist once he grows up."`,
  },
  {
    id: 123,
    amount: 1,
    categories: ['Education'],
    author: '- Sir Claus Moser',
    description: `"Education costs money. But then so does ignorance."`,
  },
  {
    id: 124,
    amount: 1,
    categories: ['Effort'],
    author: '- Woody Allen',
    description: `"Eighty percent of success is showing up."`,
  },
  {
    id: 125,
    amount: 1,
    categories: ['Creation', 'Action'],
    author: '- Benjamin Franklin',
    description: `"Either write something worth reading or do something worth writing."`,
  },
  {
    id: 126,
    amount: 1,
    categories: ['Leadership', 'Consistency'],
    author: '- Michael Jordan',
    description: `"Earn your leadership every day."`,
  },
  {
    id: 127,
    amount: 1,
    categories: ['Time Management'],
    author: '- Jim Rohn',
    description: `"Either you run the day, or the day runs you."`,
  },
  {
    id: 128,
    amount: 1,
    categories: ['Parenting', 'Leadership'],
    author: '- Dee Dee Myers',
    description: `"I am endlessly fascinated that playing football is considered a training ground for leadership, but raising children isn’t."`,
  },
  {
    id: 129,
    amount: 1,
    categories: ['Perseverance'],
    author: '- Babe Ruth',
    description: `"Every strike brings me closer to the next home run."`,
  },
  {
    id: 130,
    amount: 1,
    categories: ['Overcoming Fear'],
    author: '- George Adair',
    description: `"Everything you’ve ever wanted is on the other side of fear."`,
  },
  {
    id: 131,
    amount: 1,
    categories: ['Overcoming Fear'],
    author: '- Robert Allen',
    description: `"Fear melts when you take action towards a goal you really want."`,
  },
  {
    id: 132,
    amount: 1,
    categories: ['Leadership'],
    author: '- John Zenger',
    description: `"Great leaders are not defined by the absence of weakness, but rather by the presence of clear strengths."`,
  },
  {
    id: 133,
    amount: 1,
    categories: ['Time Management'],
    author: '- Will Rogers',
    description: `"Half our life is spent trying to find something to do with the time we have rushed through life trying to save."`,
  },
  {
    id: 134,
    amount: 1,
    categories: ['Happiness'],
    author: '- Dalai Lama',
    description: `"Happiness is not something readymade. It comes from your own actions."`,
  },
  {
    id: 135,
    amount: 1,
    categories: ['Responsibility'],
    author: '- Seneca',
    description: `"He who has great power should use it lightly."`,
  },
  {
    id: 136,
    amount: 1,
    categories: ['Leadership'],
    author: '- Aristotle',
    description: `"He who has never learned to obey cannot be a good commander."`,
  },
  {
    id: 137,
    amount: 1,
    categories: ['Change'],
    author: '- Anne Frank',
    description: `"How wonderful it is that nobody need wait a single moment before starting to improve the world."`,
  },
  {
    id: 138,
    amount: 1,
    categories: ['Innovation'],
    author: '- Henry Ford',
    description: `"I am looking for a lot of men who have an infinite capacity to not know what can't be done."`,
  },
  {
    id: 139,
    amount: 1,
    categories: ['Resilience'],
    author: '- Benjamin Franklin',
    description: `"I didn’t fail the test. I just found 100 ways to do it wrong."`,
  },
  {
    id: 140,
    amount: 1,
    categories: ['Determination'],
    author: '- Rosa Parks',
    description: `"I have learned over the years that when one’s mind is made up, this diminishes fear."`,
  },
  {
    id: 141,
    amount: 1,
    categories: ['Leadership'],
    author: '- Ralph Nader',
    description: `"I start with the premise that the function of leadership is to produce more leaders

, not more followers."`,
  },
  {
    id: 142,
    amount: 1,
    categories: ['Passion'],
    author: '- Vincent van Gogh',
    description: `"I would rather die of passion than of boredom."`,
  },
  {
    id: 143,
    amount: 1,
    categories: ['Happiness'],
    author: '- Dalai Lama',
    description: `"The purpose of our lives is to be happy."`,
  },
  {
    id: 144,
    amount: 1,
    categories: ['Imagination'],
    author: '- Maya Angelou',
    description: `"If one is lucky, a solitary fantasy can totally transform one million realities."`,
  },
  {
    id: 145,
    amount: 1,
    categories: ['Goal Setting'],
    author: '- Zig Ziglar',
    description: `"If you aim at nothing, you will hit it every time."`,
  },
  {
    id: 146,
    amount: 1,
    categories: ['Habit'],
    author: '- Tony Robbins',
    description: `"If you do what you’ve always done, you’ll get what you’ve always gotten."`,
  },
  {
    id: 147,
    amount: 1,
    categories: ['Overcoming Doubt'],
    author: '- Vincent Van Gogh',
    description: `"If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced."`,
  },
  {
    id: 148,
    amount: 1,
    categories: ['Gratitude'],
    author: '- Oprah Winfrey',
    description: `"If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough."`,
  },
  {
    id: 149,
    amount: 1,
    categories: ['Leadership'],
    author: '- John Quincy Adams',
    description: `"If your actions inspire others to dream more, learn more, do more and become more, you are a leader."`,
  },
  {
    id: 150,
    amount: 1,
    categories: ['Adaptability'],
    author: '- Thomas Jefferson',
    description: `"In matters of style, swim with the current; in matters of principle, stand like a rock."`,
  },
  {
    id: 151,
    amount: 1,
    categories: ['Motivation'],
    author: '- Brendan Burchard',
    description: `"Live fully. Love openly. Make a difference."`,
  },
  {
    id: 152,
    amount: 1,
    categories: ['will', 'time'],
    author: '- Sir John Lubbock',
    description: `"In truth, people can generally make time for what they choose to do; it is not really the time but the will that is lacking."`,
  },
  {
    id: 153,
    amount: 1,
    categories: ['progress'],
    author: '- Brian Tracy',
    description: `"It doesn't matter where you are coming from. All that matters is where you are going."`,
  },
  {
    id: 154,
    amount: 1,
    categories: ['progress'],
    author: '- Ernest Hemingway',
    description: `"It is good to have an end to journey toward; but it is the journey that matters, in the end."`,
  },
  {
    id: 155,
    amount: 1,
    categories: ['progress'],
    author: '- Peter Turla',
    description: `"It’s better to do the right thing slowly than the wrong thing quickly."`,
  },
  {
    id: 156,
    amount: 1,
    categories: ['time'],
    author: '- Lord Chesterfield',
    description: `"Know the true value of time; snatch, seize, and enjoy every moment of it. No idleness, no laziness, no procrastination; Never put off till tomorrow what you can do today."`,
  },
  {
    id: 157,
    amount: 1,
    categories: ['Inspiration'],
    author: '- Unknown',
    description: `"Know your limits, but never stop trying to exceed them."`,
  },
  {
    id: 158,
    amount: 1,
    categories: ['Inspiration'],
    author: '- Ross Perot',
    description: `"Lead and inspire people. Don’t try to manage and manipulate people. Inventories can be managed but people must be lead."`,
  },
  {
    id: 159,
    amount: 1,
    categories: ['Leadership'],
    author: '- Vince Lombardi',
    description: `"Leaders aren’t born, they are made. And they are made just like anything else, through hard work. And that’s the price we’ll have to pay to achieve that goal, or any goal."`,
  },
  {
    id: 160,
    amount: 1,
    categories: ['Life'],
    author: '- Rodin',
    description: `"Nothing is a waste of time if you use the experience wisely."`,
  },
  {
    id: 161,
    amount: 1,
    categories: ['Leadership'],
    author: '- Woodrow Wilson',
    description: `"Leadership does not always wear the harness of compromise."`,
  },
  {
    id: 162,
    amount: 1,
    categories: ['Inspiration'],
    author: '- Audrey Hepburn',
    description: `"Nothing is impossible, the word itself says, “I’m possible!”"`,
  },
  {
    id: 163,
    amount: 1,
    categories: ['Leadership'],
    author: '- General Dwight Eisenhower',
    description: `"Leadership is the art of getting someone else to do something you want done because he wants to do it."`,
  },
  {
    id: 164,
    amount: 1,
    categories: ['Life'],
    author: '- Alexander Dumas',
    description: `"Living without an aim is like sailing without a compass."`,
  },
  {
    id: 165,
    amount: 1,
    categories: ['Time'],
    author: '- Unknown',
    description: `"Money, I can only gain or lose. But time I can only lose. So, I must spend it carefully."`,
  },
  {
    id: 166,
    amount: 1,
    categories: ['Leadership'],
    author: '- Warren Bennis',
    description: `"Leadership is the capacity to translate vision into reality."`,
  },
  {
    id: 167,
    amount: 1,
    categories: ['Inspiration'],
    author: '- Unknown',
    description: `"My responsibility is getting all my players playing for the name on the front of the jersey, not the one on the back."`,
  },
  {
    id: 168,
    amount: 1,
    categories: ['Leadership'],
    author: '- Erskine Bowles',
    description: `"Leadership is the key to 99 percent of all successful efforts."`,
  },
  {
    id: 169,
    amount: 1,
    categories: ['Life'],
    author: '- Anais Nin',
    description: `"Life shrinks or expands in proportion to one’s courage."`,
  },
  {
    id: 170,
    amount: 1,
    categories: ['Leadership'],
    author: '- Bill Bradley',
    description: `"Leadership is unlocking people’s potential to become better."`,
  },
  {
    id: 171,
    amount: 1,
    categories: ['Purpose'],
    author: '- Marcus Aurelius',
    description: `"Live each day as if it be your last."`,
  },
  {
    id: 172,
    amount: 1,
    categories: ['Time'],
    author: '- Proverb',
    description: `"Lost time is never found again."`,
  },
  {
    id: 173,
    amount: 1,
    categories: ['Life'],
    author: '- Jon Bon Jovi',
    description: `"Map out your future, but do it in pencil."`,
  },
  {
    id: 174,
    amount: 1,
    categories: ['Leadership'],
    author: '- Harry S. Truman',
    description: `"Men make history and not the other way around. In periods where there is no leadership, society stands still. Progress occurs when courageous, skillful leaders seize the opportunity to change things for the better."`,
  },
  {
    id: 175,
    amount: 1,
    categories: ['Time'],
    author: '- Johann Wolfgang von Goethe',
    description: `"Nothing is ours except time."`,
  },
  {
    id: 176,
    amount: 1,
    categories: ['Purpose'],
    author: '- Henry Ford',
    description: `"Obstacles are those frightful things you see when you take your eyes off your goal."`,
  },
  {
    id: 177,
    amount: 1,
    categories: ['Life', 'Purpose'],
    author: '- Ringo Starr',
    description: `"Of course I'm ambitious. What's wrong with that? Otherwise you sleep all day."`,
  },
  {
    id: 178,
    amount: 1,
    categories: ['Life'],
    author: '- Jack Penn',
    description: `"One of the secrets of life is to make stepping-stones out of stumbling blocks."`,
  },
  {
    id: 179,
    amount: 1,
    categories: ['Life'],
    author: '- Martin Luther King Jr.',
    description: `"Our lives begin to end the day we become silent about things that matter."`,
  },
  {
    id: 180,
    amount: 1,
    categories: ['Life'],
    author: '- Dalai Lama',
    description: `"Remember that not getting what you want is sometimes a wonderful stroke of luck."`,
  },
  {
    id: 181,
    amount: 1,
    categories: ['Progress'],
    author: '- Arthur Ashe',
    description: `"Start where you are. Use what you have. Do what you can."`,
  },
  {
    id: 182,
    amount: 1,
    categories: ['Life'],
    author: '- Frank Sinatra',
    description: `"The best revenge is massive success."`,
  },
  {
    id: 183,
    amount: 1,
    categories: ['Success', 'Life'],
    author: '- Bruce Feirstein',
    description: `"The distance between insanity and genius is measured only by success."`,
  },
  {
    id: 184,
    amount: 1,
    categories: ['Leadership'],
    author: '- Max DePree',
    description: `"The first responsibility of a leader is to define reality. The last is to say thank you. In between, the leader is a servant."`,
  },
  {
    id: 185,
    amount: 1,
    categories: ['Time'],
    author: '- Stephen R. Covey',
    description: `"The key is in not spending time, but in investing it."`,
  },
  {
    id: 186,
    amount: 1,
    categories: ['Life'],
    author: '- Alice Walker',
    description: `"The most common way people give up their power is by thinking they don’t have any."`,
  },
  {
    id: 187,
    amount: 1,
    categories: ['Life'],
    author: '- Chinese Proverb',
    description: `"The person who says it cannot be done should not interrupt the person who is doing it."`,
  },
  {
    id: 188,
    amount: 1,
    categories: ['Leadership'],
    author: '- Dwight Eisenhower',
    description: `"The supreme quality of leadership is integrity."`,
  },
  {
    id: 189,
    amount: 1,
    categories: ['Time'],
    author: '- Benjamin Franklin',
    description: `"Time is money."`,
  },
  {
    id: 190,
    amount: 1,
    categories: ['Time'],
    author: '- William Penn',
    description: `"Time is what we want most, but what we use worst."`,
  },
  {
    id: 191,
    amount: 1,
    categories: ['Life'],
    author: '- Yoda',
    description: `"Try not. Do or do not. There is no try."`,
  },
  {
    id: 192,
    amount: 1,
    categories: ['Purpose'],
    author: '- James Allen',
    description: `"Until thought is linked with purpose, there is no intelligent accomplishment."`,
  },
  {
    id: 193,
    amount: 1,
    categories: ['Time'],
    author: '- Peter Drucker',
    description: `"Until we can manage time, we can manage nothing else."`,
  },
  {
    id: 194,
    amount: 1,
    categories: ['Time'],
    author: '- M. Scott Peck',
    description: `"Until you value yourself, you will not value your time. Until you value your time, you will not do anything with it."`,
  },
  {
    id: 195,
    amount: 1,
    categories: ['Life', 'Purpose'],
    author: '- Japanese Proverb',
    description: `"Vision without action is a daydream. Action without vision is a nightmare."`,
  },
  {
    id: 196,
    amount: 1,
    categories: ['Life'],
    author: '- Kevin Kruse',
    description: `"There is no such thing as failure. You either succeed or learn."`,
  },
  {
    id: 197,
    amount: 1,
    categories: ['Life'],
    author: '- Plato',
    description: `"We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light."`,
  },
  {
    id: 198,
    amount: 1,
    categories: ['Time'],
    author: '- Jim Rohn',
    description: `"We can no more afford to spend major time on minor things than we can to spend minor time on major things."`,
  },
  {
    id: 199,
    amount: 1,
    categories: ['Life', 'Purpose'],
    author: '- Erma Bombeck',
    description: `"When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me."`,
  },
  {
    id: 200,
    amount: 1,
    categories: ['Life'],
    author: '- Christopher Columbus',
    description: `"You can never cross the ocean until you have the courage to lose sight of the shore."`,
  },
  {
    id: 201,
    amount: 1,
    categories: ['Time'],
    author: '- Unknown',
    description: `"Your time is limited, don't waste it living someone else's life."`,
  },
  {
    id: 202,
    amount: 1,
    categories: ['Life', 'Progress'],
    author: '- Beverly Sills',
    description: `"You may be disappointed if you fail, but you are doomed if you don’t try."`,
  },
  {
    id: 203,
    amount: 1,
    categories: ['Life', 'Purpose'],
    author: '- Jim Rohn',
    description: `"You must get good at one of two things. Planting in the spring or begging in the fall."`,
  },
  {
    id: 204,
    amount: 1,
    categories: ['Life', 'Accountability'],
    author: '- Erica Jong',
    description: `"You take your life in your own hands, and what happens? A terrible thing, no one to blame."`,
  },
  {
    id: 205,
    amount: 1,
    categories: ['Life'],
    author: '- Lao Tzu',
    description: `"When I let go of what I am, I become what I might be."`,
  },
  {
    id: 206,
    amount: 1,
    categories: ['Life'],
    author: '- Steve Jobs',
    description: `"Have the courage to follow your heart and intuition. They somehow already know what you truly want to become."`,
  },
  {
    id: 207,
    amount: 1,
    categories: ['Life'],
    author: '- Patti Digh',
    description: `"The death rate for people who play it safe and for people who live boldly is the same: 100%."`,
  },
  {
    id: 208,
    amount: 1,
    categories: ['Life', 'Purpose'],
    author: '- Nelson Mandela',
    description: `"There is no passion to be found playing small."`,
  },
  {
    id: 209,
    amount: 1,
    categories: ['Life'],
    author: '- William Shakespeare',
    description: `"Better three hours too soon, than one minute too late."`,
  },
  {
    id: 210,
    amount: 1,
    categories: ['Life'],
    author: '- Maya Angelou',
    description: `"You can’t use up creativity. The more you use, the more you have."`,
  },
  {
    id: 211,
    amount: 1,
    categories: ['Leadership'],
    author: '- Stephen King',
    description: `"A cowardly leader is the most dangerous of men."`,
  },
  {
    id: 212,
    amount: 1,
    categories: ['Inspiration'],
    author: '- Rita Mae Brown',
    description: `"A deadline is negative inspiration. Still, it\'s better than no inspiration at all."`,
  },
  {
    id: 213,
    amount: 1,
    categories: ['Leadership'],
    author: '- Polybius',
    description: `"A good general not only sees the way to victory; he also knows when victory is impossible."`,
  },
  {
    id: 214,
    amount: 1,
    categories: ['Leadership'],
    author: '- John C. Maxwell',
    description: `"A great leader’s courage to fulfill his vision comes from passion, not position."`,
  },
  {
    id: 215,
    amount: 1,
    categories: ['Life'],
    author: '- Johann Wolfgang Von Goethe',
    description: `"A great person attracts great people and knows how to hold them together."`,
  },
  {
    id: 216,
    amount: 1,
    categories: ['Life'],
    author: '- George Bernard Shaw',
    description: `"As long as I have a want, I have a reason for living. Satisfaction is death."`,
  },
  {
    id: 217,
    amount: 1,
    categories: ['Leadership'],
    author: '- Bill Gates',
    description: `"As we look ahead into the next century, leaders will be those who empower others."`,
  },
  {
    id: 218,
    amount: 1,
    categories: ['Purpose'],
    author: '- Adolphe Monod',
    description: `"Between the great things we cannot do and the small things we will not do, the danger is that we shall do nothing."`,
  },
  {
    id: 219,
    amount: 1,
    categories: ['Life', 'Inspiration'],
    author: '- Johann Wolfgang von Goethe',
    description: `"Difficulties increase the nearer we approach the goal."`,
  },
  {
    id: 220,
    amount: 1,
    categories: ['Time'],
    author: '- H. Jackson Brown',
    description: `"Don’t say you don’t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein."`,
  },
  {
    id: 221,
    amount: 1,
    categories: ['Inspiration'],
    author: '- David Lloyd George',
    description: `"Don\'t be afraid to take a big step if one is indicated; you can\'t cross a chasm in two small jumps."`,
  },
  {
    id: 222,
    amount: 1,
    categories: ['Life'],
    author: '- Wendell Willkie',
    description: `"Education is the mother of leadership."`,
  },
  {
    id: 223,
    amount: 1,
    categories: ['Life', 'Parenting'],
    author: '- Abigail Van Buren',
    description: `"If you want your children to turn out well, spend twice as much time with them, and half as much money."`,
  },
  {
    id: 224,
    amount: 1,
    categories: ['Leadership'],
    author: '- Peter Drucker',
    description: `"Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes."`,
  },
  {
    id: 225,
    amount: 1,
    categories: ['Leadership'],
    author: '- Stephen Covey',
    description: `"Effective leadership is putting first things first. Effective management is discipline, carrying it out."`,
  },
  {
    id: 226,
    amount: 1,
    categories: ['Life'],
    author: '- Will Rogers',
    description: `"Even if you’re on the right track, you’ll get run over if you just sit there."`,
  },
  {
    id: 227,
    amount: 1,
    categories: ['Life'],
    author: '- Confucius',
    description: `"Everything has beauty, but not everyone can see."`,
  },
  {
    id: 228,
    amount: 1,
    categories: ['Life'],
    author: '- Booker T. Washington',
    description: `"Few things can help an individual more than to place responsibility on him, and to let him know that you trust him."`,
  },
  {
    id: 229,
    amount: 1,
    categories: ['Change'],
    author: '- John F. Kennedy',
    description: `"For time and the world do not stand still. Change is the law of life. And those who look only to the past or the present are certain to miss the future."`,
  },
  {
    id: 230,
    amount: 1,
    categories: ['Time'],
    author: '- John Shebbeare',
    description: `"Gaining time is gaining everything in love, trade and war."`,
  },
  {
    id: 231,
    amount: 1,
    categories: ['Goals'],
    author: '- Robert H. Schuller',
    description: `"Goals are not only absolutely necessary to motivate us. They are essential to really keep us alive."`,
  },
  {
    id: 232,
    amount: 1,
    categories: ['Goals'],
    author: '- Julius Erving',
    description: `"Goals determine what you\'re going to be."`,
  },
  {
    id: 233,
    amount: 1,
    categories: ['Life'],
    author: '- Benjamin Franklin',
    description: `"He that rises late must trot all day."`,
  },
  {
    id: 234,
    amount: 1,
    categories: ['Time'],
    author: '- Benjamin Disraeli',
    description: `"He who gains time gains everything."`,
  },
  {
    id: 235,
    amount: 1,
    categories: ['Life'],
    author: '- Dante',
    description: `"He who knows most grieves most for wasted time."`,
  },
  {
    id: 236,
    amount: 1,
    categories: ['Leadership'],
    author: '- Warren Bennis',
    description: `"I am reminded how hollow the label of leadership sometimes is and how heroic followership can be."`,
  },
  {
    id: 237,
    amount: 1,
    categories: ['Discipline'],
    author: '- Florence Nightingale',
    description: `"I attribute my success to this: I never gave or took any excuse."`,
  },
  {
    id: 238,
    amount: 1,
    categories: ['Progress'],
    author: '- Somerset Maugham',
    description: `"I don’t think of the past. The only thing that matters is the everlasting present."`,
  },
  {
    id: 239,
    amount: 1,
    categories: ['Progress', 'Purpose'],
    author: '- Leonardo da Vinci',
    description: `"I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do."`,
  },
  {
    id: 240,
    amount: 1,
    categories: ['Progress'],
    author: '- Latin Proverb',
    description: `"If the wind will not serve, take to the oars."`,
  },
  {
    id: 241,
    amount: 1,
    categories: ['Life', 'Persistence'],
    author: '- John Wooden',
    description: `"If you don\'t have time to do it right you must have time to do it over."`,
  },
  {
    id: 242,
    amount: 1,
    categories: ['Life'],
    author: '- Lawrence J. Peter',
    description: `"If you don\'t know where you are going, you will probably end up somewhere else."`,
  },
  {
    id: 243,
    amount: 1,
    categories: ['Life'],
    author: '- Henry David Thoreau',
    description: `"If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them."`,
  },
  {
    id: 244,
    amount: 1,
    categories: ['Life'],
    author: '- Swami Vivekananda',
    description: `"In a day, when you don\'t come across any problems – you can be sure that you are travelling in a wrong path."`,
  },
  {
    id: 245,
    amount: 1,
    categories: ['Focus', 'Progress'],
    author: '- Winston Churchill',
    description: `"It is a mistake to look too far ahead. Only one link of the chain of destiny can be handled at a time."`,
  },
  {
    id: 246,
    amount: 1,
    categories: ['Life', 'Discipline'],
    author: '- Latin Proverb',
    description: `"It is absurd that a man should rule others, who cannot rule himself."`,
  },
  {
    id: 247,
    amount: 1,
    categories: ['Life', 'Inspiration'],
    author: '- Arnold Bennett',
    description: `"It is easier to go down a hill than up, but the view is best from the top."`,
  },
  {
    id: 248,
    amount: 1,
    categories: ['Life'],
    author: '- George Eliot',
    description: `"It is never too late to be who you might have been."`,
  },
  {
    id: 249,
    amount: 1,
    categories: ['Parenting', 'Life'],
    author: '- Ann Landers',
    description: `"It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings."`,
  },
  {
    id: 250,
    amount: 1,
    categories: ['Life'],
    author: '- Henry David Thorea',
    description: `"It’s not enough to be busy, so are the ants. The question is, what are we busy about?"`,
  },
  {
    id: 251,
    amount: 1,
    categories: ['Accountability'],
    author: '― Steve Maraboli',
    description: `“The right thing to do and the hard thing to do are usually the same.”`,
  },
  {
    id: 252,
    amount: 1,
    categories: ['Accountability'],
    author: ' ― Thomas Paine',
    description: `“A body of men holding themselves accountable to nobody ought not to be trusted by anybody.”`,
  },

  {
    id: 253,
    amount: 1,
    categories: ['Accountability'],
    author: '― Les Brown ',
    description: `“Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.”`,
  },
  {
    id: 254,
    amount: 1,
    categories: ['Accountability'],
    author: '- Graeme Rodaughan',
    description: `“If you have not confronted true horrors, understood evil, suffered hopelessness and despair, found faith, and made yourself completely accountable for your own choices, actions and outcomes, then I can guarantee that any acceptance you pretend to have will be as brittle and temporary as a snowball in the middle of summer.”`,
  },
  {
    id: 255,
    amount: 1,
    categories: ['Accountability'],
    author: '― Steve Maraboli',
    description: `“As for the journey of life; at some point you will realize that YOU are the driver and you will drive!”`,
  },
  {
    id: 256,
    amount: 1,
    categories: ['Accountability'],
    author: '― DaShanne Stokes',
    description: `“A president cannot defend a nation if he is not held accountable to its laws.”`,
  },
  {
    id: 257,
    amount: 1,
    categories: ['Accountability'],
    author: '- Craig D. Lounsbrough',
    description: `“When I’m at the bottom looking up, the main question may not be ‘how do I get out of this hole?’ In reality, the main question might be ‘how do I get rid of the shovel that I used to dig it?”`,
  },
  {
    id: 258,
    amount: 1,
    categories: ['Accountability', 'Relatioship'],
    author: '― Rob Liano',
    description: `“The only people that can ruin a relationship or make that relationship work are the two people in it.”`,
  },
  {
    id: 259,
    amount: 1,
    categories: ['Accountability'],
    author: '― Pearl Zhu',
    description: `“Accountability means to say what you do, do what you say.”`,
  },
  {
    id: 260,
    amount: 1,
    categories: ['Accountability'],
    author: '― Jarod Kintz',
    description: `“All my failures as a human being I blame on my father. Life is about accepting responsibility, and it’s time my father started being held accountable for my deficiencies.”`,
  },
  {
    id: 261,
    amount: 1,
    categories: ['Accountability'],
    author: '― Abhijit Naskar',
    description: `“Freedom is the fulcrum of responsibility.”`,
  },
  {
    id: 262,
    amount: 1,
    categories: ['Accountability'],
    author: '― Abhijit Naskar',
    description: `“You are the nutrient,
you are the pollutant -
you are the stain,
you are the detergent.”`,
  },
  {
    id: 263,
    amount: 1,
    categories: ['Accountability'],
    author: '― Cassie Alegria',
    description: `“When you make a mistake own it and repair the damage as best you can, otherwise it will own and damage you.”`,
  },
  {
    id: 264,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“To attempt to separate power from accountability is to understand neither and be hurt by both.”`,
  },
  {
    id: 265,
    amount: 1,
    categories: ['Accountability'],
    author: '― Dr. Lucas D. Shallua',
    description: `“If you think nobody is watching, remember, you are; one day you shall be a witness against yourself.”`,
  },
  {
    id: 266,
    amount: 1,
    categories: ['Accountability'],
    author: '― Robin S. Baker',
    description: `“A person who lacks accountability will still deny the karma they're receiving, even when everything around them is burning to the ground.”`,
  },
  {
    id: 267,
    amount: 1,
    categories: ['Accountability'],
    author: '― David Goggins',
    description: `“if you look in the mirror and see someone who is obviously overweight, that means you're fucking fat”`,
  },
  {
    id: 268,
    amount: 1,
    categories: ['Accountability'],
    author: '― Abhijit Naskar',
    description: `“Revolution starts with inconvenient accountability.”`,
  },
  {
    id: 269,
    amount: 1,
    categories: ['Accountability'],
    author: '― Ash Alves',
    description: `“Holding yourself accountable empowers you. It reminds you that you have agency and choice over the decisions you make.”`,
  },
  {
    id: 270,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“How many times have we set the stage for our greatest defeats? And how many times did victory elude us because we chose to deny that fact?”`,
  },
  {
    id: 271,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“It is only in the acknowledgement of what doesn’t work that we can create sufficient space to craft something that does. And arrogance is certain to become mired in defeat because it refuses to accept the former so that it might achieve the latter.”`,
  },
  {
    id: 272,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“The most problematic mistakes are the ones that we refuse to admit.”`,
  },
  {
    id: 273,
    amount: 1,
    categories: ['Accountability'],
    author: '― Manuel Corazzari',
    description: `“without accountability there will be no growth”`,
  },
  {
    id: 274,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“It is the man or woman of wisdom who will recognize that to embrace the consequences of our choices, and to own the outcome of our behaviors is the single path to freedom, and that any other path will always, always, lead to enslavement.”`,
  },
  {
    id: 275,
    amount: 1,
    categories: ['Accountability', 'Honesty'],
    author: '― Craig D. Lounsbrough',
    description: `“To say that we don’t know is not necessarily a sign of stupidity. Rather, it is often an indication of wisdom.”`,
  },
  {
    id: 276,
    amount: 1,
    categories: ['Accountability'],
    author: '― Izey Victoria Odiase',
    description: `“There are 3 types of people you will encounter.

Those who:

(1) Promise and Deliver
(2) Under-promise and Over-deliver
(3) Over-promise and Under-deliver,
Know who you're dealing with.”`,
  },
  {
    id: 277,
    amount: 1,
    categories: ['Accountability'],
    author: '― Anthon St. Maarten',
    description: `“No more excuses. No more self-sabotage. No more self-pity. No more comparing yourself to others. Time to step up. Take action right now and start living your life with purpose.⁠”`,
  },
  {
    id: 278,
    amount: 1,
    categories: ['Accountability'],
    author: '― Dennis Prager',
    description: `“In one case, you're hoping someone else will do the right thing. In the other case, you're directing your own life, even if someone else does something stupid. Guess which path is going to be more successful.”`,
  },
  {
    id: 279,
    amount: 1,
    categories: ['Accountability'],
    author: '― Daniel Abbott',
    description: `“Accountability is the only real beginning to change.”`,
  },
  {
    id: 280,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“Forgiveness is telling ourselves that the ‘wrong’ that we did will not impede the ‘right’ that we can do.”`,
  },
  {
    id: 281,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“To do something that’s just a ‘little bit less’ than the right thing is to do a whole lot of the wrong thing.”`,
  },
  {
    id: 282,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“In the end, I walked myself here. And if ‘here’ is not the place that I wanted to be, blaming others for walking me here won’t do anything to walk me out of here.”`,
  },
  {
    id: 283,
    amount: 1,
    categories: ['Accountability'],
    author: '― Craig D. Lounsbrough',
    description: `“For, if we’re really going to give ourselves the best of ourselves, we have to be honest with the worst of ourselves.”`,
  },
  {
    id: 284,
    amount: 1,
    categories: ['Accountability'],
    author: '― Stephen Covey',
    description: `“Accountability breeds response-ability.”`,
  },
  {
    id: 285,
    amount: 1,
    categories: ['Accountability', 'Attitude'],
    author: '― Craig D. Lounsbrough',
    description: `“It’s not about what we do today. It’s about who we are everyday.”`,
  },

  {
    id: 286,
    amount: 1,
    categories: ['Attitude'],
    author: '― Marcus Aurelius ',
    description: `“If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.”`,
  },
  {
    id: 287,
    amount: 1,
    categories: ['Attitude'],
    author: '― Roy T. Bennett ',
    description: `“You Are the Master of Your Attitude

You cannot control what happens to you, but you can control the way you think about all the events. You always have a choice. You can choose to face them with a positive mental attitude.”`,
  },

  {
    id: 288,
    amount: 1,
    categories: ['Attitude'],
    author: '―― Martha Washington ',
    description: `“The greater part of our happiness or misery depends upon our dispositions, and not upon our circumstances.”`,
  },
  {
    id: 289,
    amount: 1,
    categories: ['Attitude'],
    author: '― Tom Stoppard',
    description: `“Look on every exit as being an entrance somewhere else.”`,
  },
  {
    id: 290,
    amount: 1,
    categories: ['Attitude'],
    author: '― Roy T. Bennett',
    description: `“When you take control of your attitude, you take control of your life.”`,
  },
  {
    id: 291,
    amount: 1,
    categories: ['Attitude'],
    author: '― Sherry Argov',
    description: `“Be an independent thinker at all times, and ignore anyone who attempts to define you in a limiting way.”`,
  },
  {
    id: 292,
    amount: 1,
    categories: ['Attitude'],
    author: '― Brian Tracy ',
    description: `“Positive expectations are the mark of the superior personality.”`,
  },
  {
    id: 293,
    amount: 1,
    categories: ['Attitude'],
    author: '―  Geraldine Brooks',
    description: `“To know a man's library is, in some measure, to know a man's mind.”`,
  },
  {
    id: 294,
    amount: 1,
    categories: ['Attitude'],
    author: '― Thomas Fuller ',
    description: `“A stumble may prevent a fall.”`,
  },
  {
    id: 295,
    amount: 1,
    categories: ['Attitude', 'Inspiration'],
    author: '― Dr Roopleen',
    description: `“The world’s greatest achievers have been those who have always stayed focussed on their goals and have been consistent in their efforts.”`,
  },
  {
    id: 296,
    amount: 1,
    categories: ['Attitude'],
    author: '― Michael Bassey Johnson',
    description: `“Don't pretend to be what you're not, instead, pretend to what you want to be, it is not pretence, it is a journey to self realization.”`,
  },
  {
    id: 297,
    amount: 1,
    categories: ['Attitude'],
    author: '― Captain Jack Sparrow',
    description: `“The problem is not the problem. The problem is your attitude about the problem”`,
  },
  {
    id: 298,
    amount: 1,
    categories: ['Attitude'],
    author: '― Sonia Rumzi',
    description: `“Anyone who teaches me deserves my respect, honoring and attention.”`,
  },
  {
    id: 299,
    amount: 1,
    categories: ['Attitude'],
    author: '― Lou Holtz',
    description: `“Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.”`,
  },
  {
    id: 300,
    amount: 1,
    categories: ['Attitude'],
    author: '― pablo',
    description: `“No matter how many people believe or don’t believe in you, you must be
the ultimate believer in yourself!”`,
  },
  {
    id: 301,
    amount: 1,
    categories: ['Attitude'],
    author: '― Kurt Vonnegut',
    description: `“We are what we pretend to be, so we must be careful about what we pretend to be.”`,
  },
];
